version: 2.1

# Reference:
# https://circleci.com/docs/2.0/language-javascript/
# https://github.com/cypress-io/cypress-example-kitchensink/blob/master/basic/circle.yml

# Orb to integrate Codecov
orbs:
 codecov: codecov/codecov@1.0.5
 coveralls: coveralls/coveralls@1.0.4

jobs:
  unit-tests:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          working_directory: tests # directory where steps will run
          name: install-npm-wee
          command: npm install
      # - run:
      #     working_directory: tests
      #     name: test
      #     command: npm test
      - run:
          working_directory: tests
          name: code-coverage
          command: npm run testcov
      - run:
          working_directory: tests
          name: report-code-coverage
          command: node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - store_artifacts:
          path: tests/coverage.lcov
      - run:
          working_direcory: tests
          name: move-coverage-report
          command: mkdir ../coverage && mv coverage.lcov ../coverage/lcov.info
      
      - coveralls/upload

      # Steps to push code coverage report to codecov.io
      - codecov/upload:
          file: tests/coverage.lcov
  
  ui-tests:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run:
          working_directory: tests
          name: Install dependencies
          command: npm ci
      - run:
          working_directory: tests
          command: npm run cy:verify
      - run:
          working_directory: tests
          command: npm run start:ci
          background: true
      - run:
          working_directory: tests
          command: npm run e2e:record
      # - run:
      #     working_directory: tests
      #     command: npm run lh

workflows:
  version: 2
  tests:
    jobs:
      - unit-tests
      - ui-tests