version: 2.1

# Reference:
# https://circleci.com/docs/2.0/language-javascript/
# https://github.com/cypress-io/cypress-example-kitchensink/blob/master/basic/circle.yml

# TODO - Test coverage
# Orb to integrate Codecov
#orbs:
#  codecov: codecov/codecov@1.0.5

jobs:
  unit-tests:
    docker:
      - image: circleci/node:10.16.3	
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          working_directory: tests # directory where steps will run
          name: install-npm-wee
          command: npm install
      - run:
          working_directory: tests
          name: test
          command: npm test
      #- run:
      #    name: code-coverage
      #    command: './node_modules/.bin/nyc report --reporter=text-lcov'
      #- store_artifacts:
      #    path: test-results.xml
      #    prefix: tests
      #- store_artifacts:
      #    path: coverage
      #    prefix: coverage
      #- store_test_results:
      #    path: test-results.xml

      # Steps to push code coverage report to codecov.io
      #- codecov/upload:
      #    file: <coverage report path>
  
  ui-tests:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      # restore folders with npm dependencies and Cypress binary
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      # install npm dependencies and Cypress binary
      # if they were cached, this step is super quick
      - run:
          working_directory: tests
          name: Install dependencies
          command: npm ci
      - run:
          working_directory: tests
          command: npm run cy:verify
      # save npm dependencies and Cypress binary for future runs
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      # start server before starting tests
      - run:
          working_directory: tests
          command: npm run start:ci
          background: true
      - run:
          working_directory: tests
          command: npm run e2e:record

workflows:
  version: 2
  tests:
    jobs:
      - unit-tests
      - ui-tests